config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('spammy.urls', namespace='spammy'))
]

spammy/urls.py
from django.urls import path

from config import settings
from spammy.views import spamming_system, ClientListView, NewsletterListView, MessageToSendListView, AttemptToSendListView, ClientCreateView, NewsletterCreateView, MessageToSendCreateView, ClientUpdateView, NewsletterUpdateView, MessageToSendUpdateView, change_status, ClientDeleteView, NewsletterDeleteView, MessageToSendDeleteView
from spammy.apps import SpammyConfig
from django.conf.urls.static import static

app_name = SpammyConfig.name

urlpatterns = [
    path('', spamming_system),
    path('index.html', spamming_system),

    path('clients', ClientListView.as_view(), name='client'),
    path('newsletter', NewsletterListView.as_view(), name='newsletter'),
    path('mails', MessageToSendListView.as_view(), name='mails'),
    path('maillistlog', AttemptToSendListView.as_view(), name='maillistlog'),

    path('create_client', ClientCreateView.as_view(), name='create_client'),
    path('create_newsletter', NewsletterCreateView.as_view(), name='create_newsletter'),
    path('create_mail', MessageToSendCreateView.as_view(), name='create_mail'),

    path('update_client/<int:pk>', ClientUpdateView.as_view(), name='update_client'),
    path('update_newsletter/<int:pk>', NewsletterUpdateView.as_view(), name='update_newsletter'),
    path('update_mail/<int:pk>', MessageToSendUpdateView.as_view(), name='update_mail'),
    path('status/<int:pk>/', change_status, name='status'),

    path('delete_client/<int:pk>', ClientDeleteView.as_view(), name='delete_client'),
    path('delete_newsletter/<int:pk>', NewsletterDeleteView.as_view(), name='delete_newsletter'),
    path('delete_mail/<int:pk>', MessageToSendDeleteView.as_view(), name='delete_mail'),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

spammy/models.py
from django.db import models


class Client(models.Model):
    email = models.EmailField(
        blank=False,
        max_length=100,
        verbose_name='Электронка'
    )
    mame = models.CharField(
        max_length=150,
        verbose_name='ФИО',
        default=None,
        blank=False
    )
    comment = models.TextField(verbose_name='Комментарий', default='Type here')

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

    def __str__(self):
        return f'{self.mame}\n'


class Newsletter(models.Model):
    FREQUENCYS = (
        ('once a day', 'раз в день'),
        ('once a week', 'раз в неделю'),
        ('once a month', 'раз в месяц')
    )
    STATUSES = (
        ('completed,', 'завершена'),
        ('created', 'создана'),
        ('launched', 'запущена'),
    )

    client = models.ManyToManyField(
        Client,
        verbose_name='Адресат',
    )
    posting_date = models.DateField(
        auto_now=False,
        auto_now_add=False,
        verbose_name='Когда',
        default='2023-12-29'
    )
    posting_time = models.TimeField(
        auto_now=False,
        auto_now_add=False,
        verbose_name='Во сколько',
        default='00:01'
    )
    frequency = models.CharField(choices=FREQUENCYS, default='once a day', max_length=20)
    mailing_status = models.CharField(choices=STATUSES, default='created', max_length=20)

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

    def __str__(self):
        return f'{self.posting_time}\n{self.frequency}\n{self.mailing_status}\n'

class MessageToSend(models.Model):
    newsletter = models.OneToOneField(
        Newsletter,
        verbose_name='Рассылка',
        on_delete=models.CASCADE,
        null=True
    )
    letter_subject = models.CharField(
        blank=True,
        max_length=100,
        verbose_name='Тема письма',
        default=None,
    )
    body_of_the_letter = models.TextField(
        blank=True,
        max_length=1000,
        verbose_name='Тело письма',
        default=None,
    )

    class Meta:
        verbose_name = 'Сообщение для рассылки'
        verbose_name_plural = 'Сообщение для рассылок'

    def __str__(self):
        return f'{self.letter_subject}\n{self.body_of_the_letter}\n'


class AttemptToSend(models.Model):

    date_of_last_attempt = models.CharField(max_length=100, verbose_name='Дата последней попытки', default=None)
    time_of_last_attempt = models.CharField(max_length=150, verbose_name='Время последней попытки', default=None)
    attempt_status = models.CharField(max_length=150, verbose_name='Статус попытки', default=None)
    mail_server_response = models.TextField(verbose_name='Ответ сервера', default=None)

    class Meta:
        verbose_name = 'Попытка рассылки'
        verbose_name_plural = 'Попытки рассылок'

    def __str__(self):
        return f'{self.date_of_last_attempt}\n{self.mail_server_response}\n'

spammy/views.py
from django.shortcuts import render, get_object_or_404, redirect
from spammy.models import Client, Newsletter, MessageToSend, AttemptToSend
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
import time


def spamming_system(request):
    return render(request, 'spammy/index.html')


class ClientListView(ListView):
    model = Client


class NewsletterListView(ListView):
    model = Newsletter


class MessageToSendListView(ListView):
    model = MessageToSend


class AttemptToSendListView(ListView):
    model = AttemptToSend


class ClientCreateView(CreateView):
    model = Client
    fields = ('email', 'mame', 'comment')
    success_url = reverse_lazy('spammy:client')


class NewsletterCreateView(CreateView):
    model = Newsletter
    fields = ('client', 'posting_time', 'frequency')
    success_url = reverse_lazy('spammy:create_mail')


class MessageToSendCreateView(CreateView):
    model = MessageToSend
    fields = ('newsletter', 'letter_subject', 'body_of_the_letter')
    success_url = reverse_lazy('spammy:mails')


class ClientUpdateView(UpdateView):
    model = Client
    fields = ('email', 'mame', 'comment')
    success_url = reverse_lazy('spammy:client')


class NewsletterUpdateView(UpdateView):
    model = Newsletter
    fields = ('client', 'posting_time', 'frequency')
    success_url = reverse_lazy('spammy:create_mail')


class MessageToSendUpdateView(UpdateView):
    model = MessageToSend
    fields = ('newsletter', 'letter_subject', 'body_of_the_letter')
    success_url = reverse_lazy('spammy:mails')


def change_status(request, pk):
    maillist_item = get_object_or_404(Newsletter, pk=pk)
    if maillist_item.mailing_status == 'created':
        maillist_item.mailing_status = 'launched'
    else:
        maillist_item.mailing_status = 'created'
    maillist_item.save()
    return redirect(reverse_lazy('spammy:newsletter'))

class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy('spammy:client')
class NewsletterDeleteView(DeleteView):
    model = Newsletter
    success_url = reverse_lazy('spammy:newsletter')
class MessageToSendDeleteView(DeleteView):
    model = MessageToSend
    success_url = reverse_lazy('spammy:mails')

spammy/templates/spammy/attempttosend_list.html
{% extends 'spammy/base.html' %}
{% load static %}

{% block content %}
      <div id="menubar">
        <ul id="menu">
          <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
          <li><a href="index.html">Home</a></li>
          <li><a href="{% url 'spammy:client'%}">Clients</a></li>
          <li><a href="{% url 'spammy:newsletter'%}">Maillist</a></li>
          <li><a href="{% url 'spammy:mails'%}">Mails</a></li>
          <li class="selected"><a href="{% url 'spammy:maillistlog'%}">Maillist log</a></li>
        </ul>
      </div>
    </div>
    <div id="site_content">
      <table class="table">
        <thead>
        <tr>
          <th scope="col">Дата последней попытки</th>
          <th scope="col">Время попытки</th>
		  <th scope="col">Статус попытки</th>
		  <th scope="col">Ответ сервера</th>
		  <th scope="col">Действия</th>

        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}

        <tr>
          <td>{{object.date_of_last_attempt}}</td>
          <td>{{object.time_of_last_attempt}}</td>
		  <td>{{object.attempt_status}}</td>
          <td>{{object.mail_server_response}}</td>

          <td>Редактировать - Удалить</td>

        </tr>

        {% endfor %}
        </tbody>
      </table>
    </div>
 {% endblock %}

spammy/templates/spammy/base.html
{% load static %}

<!DOCTYPE HTML>
<html>

<head>
  <title>black_pink_white</title>
  <meta name="description" content="website description" />
  <meta name="keywords" content="website keywords, website keywords" />
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <link href='{% static 'css/style.css' %}' rel="stylesheet">
  <style>
.myButton {
	box-shadow:inset 0px 1px 0px 0px #f8ece4;
	background:linear-gradient(to bottom, #f8ece4 5%, #f8ece4 100%);
	background-color:#f8ece4;
	display:inline-block;
	cursor:pointer;
	color:#f8ece4;
	font-family:Arial;
	font-size:15px;
	font-weight:bold;
	padding:6px 24px;
	text-decoration:none;
	text-shadow:0px 1px 0px #666666;
}
.myButton:hover {
	background:linear-gradient(to bottom, #f8ece4 5%, #f8ece4 100%);
	background-color:#f8ece4;
}
.myButton:active {
	position:relative;
	top:1px;

}
.GeeksForGeeks {
	maxwidth=500px;
}
  </style>


</head>

<body>
  <div id="main">
    <div id="header">
      <div id="logo">
        <div id="logo_text">
          <!-- class="logo_colour", allows you to change the colour of the text -->
          <h1><a href="#">black<span class="logo_colour">_pink</span><span class="logo_colour2">_white</span></a></h1>
          <h2>Лучше быть последним — первым, чем первым — последним.</h2>
        </div>
      </div>

    {% block content %}
    {% endblock %}

    <div id="footer">
      Copyright &copy; mailing service | <a href="#">HTML5</a> | <a href="#">CSS</a> | from <a href="#">free HTML5 templates</a>
    </div>
  </div>
</body>
</html>

spammy/templates/spammy/client_confirm_delete.html
{% extends 'spammy/base.html' %}
{% load static %}

{% block content %}
      <div id="menubar">
        <ul id="menu">
          <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
          <li><a href="index.html">Home</a></li>
          <li class="selected"><a href="{% url 'spammy:client'%}">Clients</a></li>
          <li><a href="{% url 'spammy:newsletter'%}">Maillist</a></li>
          <li><a href="{% url 'spammy:mails'%}">Mails</a></li>
          <li><a href="{% url 'spammy:maillistlog'%}">Maillist log</a></li>
        </ul>
      </div>
    </div>
    <div id="site_content">
	
	
               <form method="post">
			             <div class="form_settings">

                   {% csrf_token %}
				   <p> Are you sure? The client {{object.mame}} will be deleted </p>
				   <a href='{% url 'spammy:client' %}'> не удалять </a>
                   <button class="btn btn-primary" type="submit">
                       удалить
                   </button>
				   </div>
               </form>
    

	
	</div>
{% endblock %}

spammy/templates/spammy/client_form.html
{% extends 'spammy/base.html' %}
{% load static %}

{% block content %}
      <div id="menubar">
        <ul id="menu">
          <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
          <li><a href="index.html">Home</a></li>
          <li class="selected"><a href="{% url 'spammy:client'%}">Clients</a></li>
          <li><a href="{% url 'spammy:newsletter'%}">Maillist</a></li>
          <li><a href="{% url 'spammy:mails'%}">Mails</a></li>
          <li><a href="{% url 'spammy:maillistlog'%}">Maillist log</a></li>
        </ul>
      </div>
    </div>
    <div id="site_content">
	
	
               <form method="post">
			             <div class="form_settings">

                   {% csrf_token %}
				   
                   {{ form.as_ul }}
	
                   <button class="btn btn-primary" type="submit">
                       сохранить
                   </button>
				   </div>
               </form>
    

	
	</div>
{% endblock %}

spammy/templates/spammy/client_list.html
{% extends 'spammy/base.html' %}
{% load static %}

{% block content %}
      <div id="menubar">
        <ul id="menu">
          <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
          <li><a href="index.html">Home</a></li>
          <li class="selected"><a href="{% url 'spammy:client'%}">Clients</a></li>
          <li><a href="{% url 'spammy:newsletter'%}">Maillist</a></li>
          <li><a href="{% url 'spammy:mails'%}">Mails</a></li>
          <li><a href="{% url 'spammy:maillistlog'%}">Maillist log</a></li>
        </ul>
      </div>
    </div>
    <div id="site_content">
      <table class="table">
        <thead>
        <tr>
          <th scope="col">Контактный email</th>
          <th scope="col">ФИО</th>
          <th scope="col">Комментарий</th>
          <th scope="col">Действия</th>

        </tr>
        </thead>
        <tbody>
				     <a href="{% url 'spammy:create_client' %}">Add new client</a>

        {% for object in object_list %}

        <tr>
          <td>{{object.email}}</td>
          <td>{{object.mame}}</td>
          <td>{{object.comment|truncatechars:30}}</td>
          <td>
		  <a href='{% url 'spammy:update_client' object.pk %}'>Редактировать</a>  - 
		  <a href='{% url 'spammy:delete_client' object.pk %}'>Удалить</a></td>

        </tr>

        {% endfor %}
        </tbody>
      </table>
	  <a href="{% url 'spammy:create_client' %}">Add new client</a>
    </div>
{% endblock %}

spammy/templates/spammy/index.html
{% extends 'spammy/base.html' %}
{% load static %}

{% block content %}
      <div id="menubar">
        <ul id="menu">
          <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
          <li class="selected"><a href="index.html">Home</a></li>
          <li><a href="{% url 'spammy:client'%}">Clients</a></li>
          <li><a href="{% url 'spammy:newsletter'%}">Maillist</a></li>
          <li><a href="{% url 'spammy:mails'%}">Mails</a></li>
          <li><a href="{% url 'spammy:maillistlog'%}">Maillist log</a></li>
        </ul>
      </div>
    </div>
    <div id="site_content">
      <div class="sidebar">
        <!-- insert your sidebar items here -->
        <h3>Latest News</h3>
        <h4>New Website Launched</h4>
        <h5>August 1st, 2014</h5>
        <p>2014 sees the redesign of our website. Take a look around and let us know what you think.<br /><a href="#">Read more</a></p>
        <p></p>
        <h4>New Website Launched</h4>
        <h5>August 1st, 2014</h5>
        <p>2014 sees the redesign of our website. Take a look around and let us know what you think.<br /><a href="#">Read more</a></p>
        <h3>Useful Links</h3>
        <ul>
          <li><a href="#">link 1</a></li>
          <li><a href="#">link 2</a></li>
          <li><a href="#">link 3</a></li>
          <li><a href="#">link 4</a></li>
        </ul>
        <h3>Search</h3>
        <form method="post" action="#" id="search_form">
          <p>
            <input class="search" type="text" name="search_field" value="Enter keywords....." />
            <input name="search" type="image" style="width: 30px; border: 0; margin: 0 0 -9px 5px;" src="https://gifimage.net/wp-content/uploads/2017/08/small-gif-16.gif" alt="Search" title="Search" />
          </p>
        </form>
      </div>
      <div id="content">
        <!-- insert the page content here -->
        <h1>Welcome to the mailing service</h1>
        <DIV class="block"><img src="https://upyachka.io/img/kot/02.gif"><img src="https://upyachka.io/img/kot/80.gif"><img src="https://upyachka.io/img/kot/15.gif"><<img src="https://upyachka.io/img/kot/104.gif"></DIV>
        <DIV class="block"><img src="https://upyachka.io/img/kot/23.gif"><img src="https://upyachka.io/img/kot/03.gif"><img src="https://upyachka.io/img/kot/16.gif"><img src="https://upyachka.io/img/kot/21.gif"></DIV>
        <DIV class="block"><img src="https://upyachka.io/img/kot/110.gif"><img src="https://upyachka.io/img/kot/24.gif"><img src="https://upyachka.io/img/kot/18.gif"><img src="https://upyachka.io/img/kot/11.gif"></DIV>
        <DIV class="block"><img src="https://upyachka.io/img/kot/103.gif"><img src="https://upyachka.io/img/kot/04.gif"><img src="https://upyachka.io/img/kot/05.gif"><img src="https://upyachka.io/img/kot/17.gif"></DIV>
        <DIV class="block"><img src="https://upyachka.io/img/kot/31.gif"></DIV>
        </div>
      </div>
    </div>
 {% endblock %}

spammy/templates/spammy/messagetosend_confirm_delete.html
{% extends 'spammy/base.html' %}
{% load static %}

{% block content %}
      <div id="menubar">
        <ul id="menu">
          <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
          <li><a href="index.html">Home</a></li>
          <li><a href="{% url 'spammy:client'%}">Clients</a></li>
          <li><a href="{% url 'spammy:newsletter'%}">Maillist</a></li>
          <li class="selected"><a href="{% url 'spammy:mails'%}">Mails</a></li>
          <li><a href="{% url 'spammy:maillistlog'%}">Maillist log</a></li>
        </ul>
      </div>
    </div>
    <div id="site_content">
	
	
               <form method="post">
			             <div class="form_settings">

                   {% csrf_token %}
				   <p> Are you sure? The message {{object.letter_subject}} will be deleted </p>
				   <a href='{% url 'spammy:mails' %}'> не удалять </a>
                   <button class="btn btn-primary" type="submit">
                    удалить
                   </button>
				   </div>
               </form>
    

	
	</div>
{% endblock %}

spammy/templates/spammy/messagetosend_form.html
{% extends 'spammy/base.html' %}
{% load static %}

{% block content %}
      <div id="menubar">
        <ul id="menu">
          <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
          <li><a href="index.html">Home</a></li>
          <li><a href="{% url 'spammy:client'%}">Clients</a></li>
          <li><a href="{% url 'spammy:newsletter'%}">Maillist</a></li>
          <li class="selected"><a href="{% url 'spammy:mails'%}">Mails</a></li>
          <li><a href="{% url 'spammy:maillistlog'%}">Maillist log</a></li>
        </ul>
      </div>
    </div>
    <div id="site_content">
	
	
               <form method="post">
			             <div class="form_settings">

                   {% csrf_token %}
				   
                   {{ form.as_ul }}
	
                   <button class="btn btn-primary" type="submit">
                       сохранить
                   </button>
				   </div>
               </form>
    

	
	</div>
{% endblock %}

spammy/templates/spammy/messagetosend_list.html
{% extends 'spammy/base.html' %}
{% load static %}

{% block content %}
      <div id="menubar">
        <ul id="menu">
          <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
          <li><a href="index.html">Home</a></li>
          <li><a href="{% url 'spammy:client'%}">Clients</a></li>
          <li><a href="{% url 'spammy:newsletter'%}">Maillist</a></li>
          <li class="selected"><a href="{% url 'spammy:mails'%}">Mails</a></li>
          <li><a href="{% url 'spammy:maillistlog'%}">Maillist log</a></li>
        </ul>
      </div>
    </div>
    <div id="site_content">
      <table class="table">
        <thead>
        <tr>
          <th scope="col">Рассылка</th>
          <th scope="col">Тема</th>
          <th scope="col">Текст</th>
		  <th scope="col">Действия</th>

        </tr>
        </thead>
        <tbody>
		     <a href="{% url 'spammy:create_mail' %}">Add new message</a>

        {% for object in object_list %}

        <tr class = "GeeksForGeeks">
          <td>{{object.newsletter}}</td>
          <td>{{object.letter_subject}}</td>
          <td><p>{{object.body_of_the_letter|truncatechars:30}}</p></td>
          <td>
		  <a href='{% url 'spammy:update_mail' object.pk %}'>Редактировать</a> - 
		  <a href='{% url 'spammy:delete_mail' object.pk %}'>Удалить</a>
		  </td>

        </tr>

        {% endfor %}
        </tbody>
      </table>
     <a href="{% url 'spammy:create_mail' %}">Add new message</a>
    </div>
 {% endblock %}

spammy/templates/spammy/newsletter_confirm_delete.html
{% extends 'spammy/base.html' %}
{% load static %}

{% block content %}
      <div id="menubar">
        <ul id="menu">
          <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
          <li><a href="index.html">Home</a></li>
          <li><a href="{% url 'spammy:client'%}">Clients</a></li>
          <li class="selected"><a href="{% url 'spammy:newsletter'%}">Maillist</a></li>
          <li><a href="{% url 'spammy:mails'%}">Mails</a></li>
          <li><a href="{% url 'spammy:maillistlog'%}">Maillist log</a></li>
        </ul>
      </div>
    </div>
    <div id="site_content">
	
	
               <form method="post">
			             <div class="form_settings">

                   {% csrf_token %}
				   	<p> Are you sure? The maillist {{object.posting_date}} {{object.posting_time}} will be deleted </p>
				   <a href='{% url 'spammy:newsletter' %}'> не удалять </a>
                   <button class="btn btn-primary" type="submit">
                       удалить
                   </button>
				   </div>
               </form>
    

	
	</div>
{% endblock %}

spammy/templates/spammy/newsletter_form.html
{% extends 'spammy/base.html' %}
{% load static %}

{% block content %}
      <div id="menubar">
        <ul id="menu">
          <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
          <li><a href="index.html">Home</a></li>
          <li><a href="{% url 'spammy:client'%}">Clients</a></li>
          <li class="selected"><a href="{% url 'spammy:newsletter'%}">Maillist</a></li>
          <li><a href="{% url 'spammy:mails'%}">Mails</a></li>
          <li><a href="{% url 'spammy:maillistlog'%}">Maillist log</a></li>
        </ul>
      </div>
    </div>
    <div id="site_content">
	
	
               <form method="post">
			             <div class="form_settings">

                   {% csrf_token %}
				   
                   {{ form.as_ul }}
	
                   <button class="btn btn-primary" type="submit">
                       сохранить
                   </button>
				   </div>
               </form>
    

	
	</div>
{% endblock %}

spammy/templates/spammy/newsletter_list.html
{% extends 'spammy/base.html' %}
{% load static %}

{% block content %}
      <div id="menubar">
        <ul id="menu">
          <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
          <li><a href="index.html">Home</a></li>
          <li><a href="{% url 'spammy:client'%}">Clients</a></li>
          <li class="selected"><a href="{% url 'spammy:newsletter'%}">Maillist</a></li>
          <li><a href="{% url 'spammy:mails'%}">Mails</a></li>
          <li><a href="{% url 'spammy:maillistlog'%}">Maillist log</a></li>
        </ul>
      </div>
    </div>
    <div id="site_content">
      <table class="table">
        <thead>
        <tr>
          <th scope="col">Клиент</th>
          <th scope="col">Время</th>
          <th scope="col">Частота</th>
          <th scope="col">Статус</th>
		  <th scope="col">Действия</th>

        </tr>
        </thead>
        <tbody>
		     <a href="{% url 'spammy:create_newsletter' %}">Add new newsletter</a>

        {% for object in object_list %}

        <tr>
          <td>{{object.client}}</td>
          <td>{{object.posting_time}}</td>
          <td>{{object.frequency}}</td>
		  <td>
		  {{object.mailing_status}}
		  {%  if object.mailing_status == 'created' %}
			<a href='{% url 'spammy:status' object.pk %}'> - start mailinglist</a>
		  {% else %}
			<a href='{% url 'spammy:status' object.pk %}'> - stop mailinglist</a>
			{% endif %}
		  </td>
          <td>
		  <a href='{% url 'spammy:update_newsletter' object.pk %}'>Редактировать</a> - 
		  <a href='{% url 'spammy:delete_newsletter' object.pk %}'>Удалить</a>
		  </td>

        </tr>

        {% endfor %}
        </tbody>
      </table>
     <a href="{% url 'spammy:create_newsletter' %}">Add new newsletter</a>
    </div>
 {% endblock %}